### PR TITLE
Create input.css

### PR DESCRIPTION
**Pull request by raman1999**
feat: added style for input
image

### CODE REVIEW

**Review by shubhamkumar648 — COMMENTED** [review]
you could also used rem for better web performance like rem instead of px

**Comment by raman1999** [comment]
Hey, I have used rem mostly, only for unit less than 10px ,I used px instead of rem

**Comment by SimranjitKaurMaan** [comment]
You could maintain spacing between the input field and search icon.

**Review by SimranjitKaurMaan — COMMENTED** [review]
You could maintain spacing between the input field and search icon.

**Comment by raman1999** [comment]
Thanks for suggesting , but for my personal preference , I like without space

**Pull request merged**
